
services:
  backend:
    build: 
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      #mysql
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      #redis
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      #s3
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
      NODE_ENV: ${NODE_ENV}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      #gemini
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ["./runner.sh"]
    command: [ "node", "app.js" ]

  db:
    image: mysql:8
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    
volumes:
  db-data:
  redis-data:
